{
 "title": "Hashicorp Vault - Integrated storage (Raft)",
 "description": " Hashicorp Vault with Integrated storage (Raft) Metrics",
 "tags": [
  "vault",
  "integrated-storage-raft"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(vault_core_active,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(vault_core_active{namespace=\"$namespace\"},job)"
    }
   },
   {
    "name": "task",
    "query": {
     "query": "label_values(vault_core_active{job=\"$job\"},task)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_autopilot_healthy{job=\"$job\"}",
     "legendFormat": "Leader: {{ task }}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vault_raft_state_candidate{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fault tolerance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vault_autopilot_failure_tolerance{job=\"$job\"}",
     "legendFormat": "fault tolerance"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Sealed Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(1 + vault_core_unsealed{job=\"$job\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Secrets",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 5 },
   "targets": [
    {
     "expr": "avg without(instance) (vault_secret_kv_count{job=\"$job\"})",
     "legendFormat": "{{ mount_point }}"
    }
   ]
  },
  {
   "title": "Number of Leases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_expire_num_leases{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Identity Entities Aliases by Method",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(instance) (vault_identity_entity_alias_count{job=\"$job\"})",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Healthy Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"$job\"}",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Number of Identity Entities",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_identity_num_entities{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Token",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Available Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vault_token_count{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Tokens by Policy",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 14 },
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_policy{job=\"$job\"})",
     "legendFormat": "{{ policy }}"
    }
   ]
  },
  {
   "title": "Pending Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_token_create_count{job=\"$job\"} - vault_token_store_count{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Tokens by TTL",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_ttl{job=\"$job\"})",
     "legendFormat": "{{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Tokens by Auth Method",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_count_by_auth{job=\"$job\"})",
     "legendFormat": "{{ auth_method }}"
    }
   ]
  },
  {
   "title": "Tokens Creation by Method & TTL",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(auth_methodcreation_ttl) (vault_token_creation{job=\"$job\"})",
     "legendFormat": "{{ auth_method }} - {{ creation_ttl }}"
    }
   ]
  },
  {
   "title": "Token Creation/Storage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg without(instance) (vault_token_create_count{job=\"$job\"})",
     "legendFormat": "Create"
    },
    {
     "expr": "avg without(instance) (vault_token_store_count{job=\"$job\"})",
     "legendFormat": "Store"
    }
   ]
  },
  {
   "title": "Token Lookups",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(vault_token_lookup_count{job=\"$job\"}[1m]))",
     "legendFormat": "Lookups"
    }
   ]
  },
  {
   "title": "Audit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Log Request Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_request_failure{job=\"$job\"}[1m]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Log Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(vault_audit_log_request_count{job=\"$job\"}[1m]))",
     "legendFormat": "Request "
    },
    {
     "expr": "avg(irate(vault_audit_log_response_count{job=\"$job\"}[1m]))",
     "legendFormat": "Response"
    },
    {
     "expr": "avg(irate(vault_core_handle_request_count{job=\"$job\"}[1m]))",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Log Response Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(idelta(vault_audit_log_response_failure{job=\"$job\"}[1m]))",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Policy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Policy Set",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(vault_policy_set_policy_count{job=\"$job\"}[1m]))",
     "legendFormat": "SET"
    }
   ]
  },
  {
   "title": "Policy Get",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(irate(vault_policy_get_policy_count{job=\"$job\"}[1m]))",
     "legendFormat": "GET"
    }
   ]
  },
  { "title": "Integrated storage (Raft)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Election Events",
   "type": "status-history",
   "description": "This panel should show no activity in a stable cluster. Some leadership transition events are expectedsuch as during cluster upgrades. Unexpected events may indicate an issue with cluster stability",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "increase(vault_raft_state_candidate{job=\"$job\"}[1m]) > 0",
     "legendFormat": "{{ task }} - candidate"
    },
    {
     "expr": "increase(vault_raft_state_leader{job=\"$job\"}[1m]) > 0",
     "legendFormat": "{{ task }} - leader"
    }
   ]
  },
  {
   "title": "Raft FSM apply",
   "type": "timeseries",
   "description": "Time it takes for a server to apply Raft entries to the internal state machine.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (vault_raft_fsm_applyBatch{job=\"$job\", quantile=\"0.9\"}) by (task)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raft Dispatch Log",
   "type": "timeseries",
   "description": "Time to write logmark in flightand start replication to followers",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (vault_raft_leader_dispatchLog{job=\"$job\", quantile=\"0.9\"}) by (task)",
     "legendFormat": "Time"
    },
    {
     "expr": "sum (increase(vault_raft_leader_dispatchNumLogs{job=\"$job\"}[$__rate_interval]))  by (task)",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Raft Append Entries",
   "type": "timeseries",
   "description": "The time it takes for a Raft transaction to be replicated to a quorum of followers",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (vault_raft_rpc_appendEntries{job=\"$job\", quantile=\"0.9\"}) by (task)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raft Commit Time",
   "type": "timeseries",
   "description": "Time difference between when a message was first passed into Raft and when the resulting commit took place on the leader",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (vault_raft_commitTime{job=\"$job\"}) by (quantile, task)",
     "legendFormat": "{{quantile}}% ({{task}})"
    }
   ]
  },
  {
   "title": "Raft Replication Heartbeat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (vault_raft_replication_heartbeat{job=\"$job\", quantile=\"0.9\"}) by (task)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leader Last Contacted",
   "type": "timeseries",
   "description": "Measures the time since the leader was last able to contact the follower nodes when checking its leader lease",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (vault_raft_leader_lastContact{job=\"$job\", quantile=\"0.9\"}) by (task)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log replication from leader to servers",
   "type": "timeseries",
   "description": "This measures the time it takes to replicate log entries to followers. This is a general indicator of the load pressure on the Consul serversas well as the performance of the communication between the servers.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum (vault_raft_replication_appendEntries_rpc{job=\"$job\", quantile=\"0.9\"}) by (task)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raft Apply Count",
   "type": "timeseries",
   "description": "Number of Raft transactions - general indicator of the write load on the servers.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (increase(vault_raft_apply{job=\"$job\"}[$__rate_interval])) by (task)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raft Applied Index",
   "type": "bargauge",
   "description": "Current index applied to FSM",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (vault_raft_storage_stats_applied_index{job=\"$job\"}) by (task)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stats: $task",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "repeat": "task",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Sealed Status",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max(1 + vault_core_unsealed{job=\"$job\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Heap Objects Used",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(vault_runtime_heap_objects{job=\"$job\", task=~\"$task\"} / vault_runtime_malloc_count{job=\"$job\", task=~\"$task\"})"
      }
     ]
    },
    {
     "title": "Number of Goroutines",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(vault_runtime_num_goroutines{job=\"$job\", task=~\"$task\"})"
      }
     ]
    },
    {
     "title": "Allocated MB",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(vault_runtime_alloc_bytes{job=\"$job\", task=~\"$task\"})",
       "legendFormat": "$task"
      }
     ]
    }
   ]
  }
 ]
}