{
 "title": "Vault - Integrated Storage (Raft)",
 "tags": [
  "hashicorp",
  "vault",
  "integrated-storage",
  "raft"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(vault_core_active,job)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(vault_core_active{job=\"$job\"},namespace)"
    }
   },
   {
    "name": "task",
    "query": {
     "query": "label_values(vault_core_active{job=\"$job\", namespace=\"$namespace\"},task)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Core system", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes status",
   "type": "stat",
   "description": "Indicates whether all nodes are healthy",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "0 + vault_autopilot_healthy{job=\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seal status",
   "type": "stat",
   "description": "Indicates whether Vault is currently unsealed",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(1 + vault_core_unsealed{job=\"$job\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "description": "The number of peers in the raft cluster configuration\n",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "0 + vault_raft_peers{job=\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure tolerance",
   "type": "stat",
   "description": "The number of healthy nodes in excess of quorum",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "0 + vault_autopilot_failure_tolerance{job=\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request handle count/s",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(vault_core_handle_request_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "request (overall per-second rate)"
    },
    {
     "expr": "sum(rate(vault_core_handle_login_request_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "login (overall per-second rate)"
    }
   ]
  },
  {
   "title": "Barrier operation count/s",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(vault_barrier_get_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(rate(vault_barrier_put_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "sum(rate(vault_barrier_delete_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Policy operation count/s",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(vault_policy_get_policy_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(rate(vault_policy_set_policy_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "SET"
    },
    {
     "expr": "sum(rate(vault_policy_delete_policy_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Metric collection count/s",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(vault_metrics_collection_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "collect (overall per-second rate)"
    }
   ]
  },
  { "title": "Raft telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Leader last contacted",
   "type": "timeseries",
   "description": "Measures the time since the leader was last able to contact the follower nodes when checking its leader lease",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (namespace) (vault_raft_leader_lastContact{job=\"$job\", namespace=\"$namespace\", quantile=\"0.9\"})",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Raft dispatch log",
   "type": "timeseries",
   "description": "Time required for the leader node to write a log entry to disk",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (namespace) (vault_raft_leader_dispatchLog{job=\"$job\", namespace=\"$namespace\"})",
     "legendFormat": "Time"
    },
    {
     "expr": "sum by (namespace) (increase(vault_raft_leader_dispatchNumLogs{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Logs"
    }
   ]
  },
  {
   "title": "Raft replication heartbeat",
   "type": "timeseries",
   "description": "Time required to invoke `appendEntries` on a peer so the peer does not time out",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (namespace) (vault_raft_replication_heartbeat{job=\"$job\", namespace=\"$namespace\", quantile=\"0.9\"})",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Raft append entries",
   "type": "timeseries",
   "description": "The time it takes for a Raft transaction to be replicated to a quorum of followers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (namespace) (vault_raft_rpc_appendEntries{job=\"$job\", namespace=\"$namespace\", quantile=\"0.9\"})",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Election events",
   "type": "status-history",
   "description": "This panel should show no activity in a stable cluster. Some leadership transition events are expected such as during cluster upgrades. Unexpected events may indicate an issue with cluster stability",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (namespace) (increase(vault_raft_state_candidate{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "candidate"
    },
    {
     "expr": "sum by (namespace) (increase(vault_raft_state_leader{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "leader"
    }
   ]
  },
  {
   "title": "Raft commit time",
   "type": "timeseries",
   "description": "Time difference between when a message was first passed into Raft and when the resulting commit took place on the leader",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vault_raft_commitTime{job=\"$job\", namespace=\"$namespace\", quantile=\"0.9\"}",
     "legendFormat": "P90"
    }
   ]
  },
  {
   "title": "Raft apply index",
   "type": "bargauge",
   "description": "Current index applied to FSM",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (task) (vault_raft_storage_stats_applied_index{job=\"$job\", namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raft fsm apply",
   "type": "timeseries",
   "description": "Time it takes for a server to apply Raft entries to the internal state machine.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (task) (vault_raft_fsm_applyBatch{job=\"$job\", namespace=\"$namespace\", quantile=\"0.9\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Mount table",
   "type": "bargauge",
   "description": "Number of mounts in the given mount table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (vault_core_mount_table_num_entries{job=\"$job\", namespace=\"$namespace\", local=\"false\", type=\"auth\"})",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum by (type) (vault_core_mount_table_num_entries{job=\"$job\", namespace=\"$namespace\", local=\"false\", type=\"logical\"} - 1)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Mount table size",
   "type": "bargauge",
   "description": "The current size of the relevant mount table.  \nIntegrated storage default (1 MiB): ~14000",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (vault_core_mount_table_size{job=\"$job\", namespace=\"$namespace\", local=\"false\", type=\"auth\"} / 1000)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum by (type) (vault_core_mount_table_size{job=\"$job\", namespace=\"$namespace\", local=\"false\", type=\"logical\"} / 1000)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Stats: $task",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "repeat": "task",
   "collapsed": true,
   "panels": [
    {
     "title": "Sealed Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "vault_core_active{job=\"$job\", task=~\"$task\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Sealed Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max(1 + vault_core_unsealed{job=\"$job\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Heap Objects Used",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(vault_runtime_heap_objects{job=\"$job\", task=~\"$task\"} / vault_runtime_malloc_count{job=\"$job\", task=~\"$task\"})"
      }
     ]
    },
    {
     "title": "Number of Goroutines",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(vault_runtime_num_goroutines{job=\"$job\", task=~\"$task\"})"
      }
     ]
    },
    {
     "title": "Allocated MB",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 10, "x": 14, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(vault_runtime_alloc_bytes{job=\"$job\", task=~\"$task\"})",
       "legendFormat": "$task"
      }
     ]
    }
   ]
  }
 ]
}