{
 "title": "Vault - Node Stats",
 "tags": [
  "hashicorp",
  "vault",
  "integrated-storage",
  "raft"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(vault_core_active,job)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(vault_core_active{job=\"$job\"},namespace)"
    }
   },
   {
    "name": "task",
    "query": {
     "query": "label_values(vault_core_active{job=\"$job\", namespace=\"$namespace\"},task)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node: $task", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "task" },
  {
   "title": "Sealed Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vault_core_active{job=\"$job\", task=~\"$task\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sealed Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(1 + vault_core_unsealed{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Objects Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_heap_objects{job=\"$job\", task=~\"$task\"} / vault_runtime_malloc_count{job=\"$job\", task=~\"$task\"})"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_num_goroutines{job=\"$job\", task=~\"$task\"})"
    }
   ]
  },
  {
   "title": "Allocated MB",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(vault_runtime_alloc_bytes{job=\"$job\", task=~\"$task\"})",
     "legendFormat": "$task"
    }
   ]
  },
  {
   "title": "Request handle count/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(vault_core_handle_request_count{job=\"$job\", namespace=\"$namespace\", task=~\"$task\"}[$__rate_interval]))",
     "legendFormat": "request (overall per-second rate)"
    },
    {
     "expr": "sum(rate(vault_core_handle_login_request_count{job=\"$job\", namespace=\"$namespace\", task=~\"$task\"}[$__rate_interval]))",
     "legendFormat": "login (overall per-second rate)"
    }
   ]
  },
  {
   "title": "Policy operation count/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(vault_policy_get_policy_count{job=\"$job\", namespace=\"$namespace\", task=~\"$task\"}[$__rate_interval]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(rate(vault_policy_set_policy_count{job=\"$job\", namespace=\"$namespace\", task=~\"$task\"}[$__rate_interval]))",
     "legendFormat": "SET"
    },
    {
     "expr": "sum(rate(vault_policy_delete_policy_count{job=\"$job\", namespace=\"$namespace\", task=~\"$task\"}[$__rate_interval]))",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Barrier operation count/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(vault_barrier_get_count{job=\"$job\", namespace=\"$namespace\", task=~\"$task\"}[$__rate_interval]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(rate(vault_barrier_put_count{job=\"$job\", namespace=\"$namespace\", task=~\"$task\"}[$__rate_interval]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "sum(rate(vault_barrier_delete_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "DELETE"
    }
   ]
  }
 ]
}