{
 "title": "Vault - Stats",
 "tags": [
  "hashicorp",
  "vault",
  "integrated-storage",
  "raft"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(vault_core_active,job)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(vault_core_active{job=\"$job\"},namespace)"
    }
   },
   {
    "name": "task",
    "query": {
     "query": "label_values(vault_core_active{job=\"$job\", namespace=\"$namespace\"},task)"
    }
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request handle count/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(vault_core_handle_request_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "request (overall per-second rate)"
    },
    {
     "expr": "sum(rate(vault_core_handle_login_request_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "login (overall per-second rate)"
    }
   ]
  },
  {
   "title": "Barrier operation count/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(vault_barrier_get_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(rate(vault_barrier_put_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "PUT"
    },
    {
     "expr": "sum(rate(vault_barrier_delete_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "DELETE"
    }
   ]
  },
  {
   "title": "Metric collection count/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(vault_metrics_collection_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "collect (overall per-second rate)"
    }
   ]
  },
  {
   "title": "Policy operation count/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(vault_policy_get_policy_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "GET"
    },
    {
     "expr": "sum(rate(vault_policy_set_policy_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "SET"
    },
    {
     "expr": "sum(rate(vault_policy_delete_policy_count{job=\"$job\", namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "DELETE"
    }
   ]
  },
  { "title": "Identity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Identity entitys",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vault_identity_entity_count{job=\"$job\", namespace=\"$namespace\"} + 0)",
     "legendFormat": "entity"
    },
    {
     "expr": "sum(vault_identity_entity_alias_count{job=\"$job\", namespace=\"$namespace\"} + 0)",
     "legendFormat": "alias"
    }
   ]
  },
  {
   "title": "Identity upsert (ms)",
   "type": "heatmap",
   "description": "Time required to upsert an groups/entities to the in-memory database and, on the active node, persist the data to storage",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(vault_identity_upsert_entity_txn{job=\"$job\", namespace=\"$namespace\", quantile=\"0.9\"})",
     "legendFormat": "entity"
    },
    {
     "expr": "sum(vault_identity_upsert_group_txn{job=\"$job\", namespace=\"$namespace\", quantile=\"0.9\"})",
     "legendFormat": "group"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Mount table",
   "type": "bargauge",
   "description": "Number of mounts in the given mount table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (vault_core_mount_table_num_entries{job=\"$job\", namespace=\"$namespace\", local=\"false\", type=\"auth\"})",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum by (type) (vault_core_mount_table_num_entries{job=\"$job\", namespace=\"$namespace\", local=\"false\", type=\"logical\"} - 1)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Mount table size",
   "type": "bargauge",
   "description": "The current size of the relevant mount table.  \nIntegrated storage default (1 MiB): ~14000",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (vault_core_mount_table_size{job=\"$job\", namespace=\"$namespace\", local=\"false\", type=\"auth\"} / 1000)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum by (type) (vault_core_mount_table_size{job=\"$job\", namespace=\"$namespace\", local=\"false\", type=\"logical\"} / 1000)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}